steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: AR_AUTH
    args: ["auth", "configure-docker", "${LOCATION}-docker.pkg.dev" ]
  - name: "gcr.io/cloud-builders/docker"
    id: DOCKER_BUILD
    args: ["build",
           "--pull",
           "--no-cache",
           "--build-arg", "BASE_IMAGE=${_AR_DOCKER_REPO}/${_BASE_IMAGE}",
           "--build-arg", "PIP_INDEX_URL=${_AR_PIP_REPO}",
           "--build-arg", "PIP_INSTALL_ARG=${_PIP_INSTALL_ARG}",
           "--tag", "${_IMAGE_NAME}",
           "--tag", "${_DOCKER_IMAGE_LATEST}",
           "--tag", "${_DOCKER_IMAGE_SHA}",
           "--file", "${_DOCKERFILE}",
           "${_CODE_DIR}"]

logsBucket: "gs://${_BUCKET_NAME}/cloudbuild_logs/"

options:
  dynamic_substitutions: true
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: E2_HIGHCPU_32
  substitution_option: "ALLOW_LOOSE"

substitutions:
  _CODE_DIR: "./code"
  _DOCKERFILE: ""
  _PIP_INSTALL_ARG: ""
  _BASE_IMAGE: ""
  _IMAGE_NAME: ""
  _AR_DOCKER_REPO: ""
  _AR_PIP_REPO: ""
  _DOCKER_IMAGE_LATEST: "${_AR_DOCKER_REPO}/${_IMAGE_NAME}:latest"
  _DOCKER_IMAGE_SHA: "${_AR_DOCKER_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"

images:
  - "${_DOCKER_IMAGE_LATEST}"
  - "${_DOCKER_IMAGE_SHA}"