steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build",
           "--pull",
           "--no-cache",
           "--build-arg",
            "BASE_IMAGE=${_BASE_IMAGE}",
            "PIP_INDEX_URL=${_AR_PIP_REPO}",
            "PIP_INSTALL_ARG=${_PIP_INSTALL_ARG}",
           "--tag", "${_IMAGE_NAME}",
           "--tag", "${_DOCKER_IMAGE}",
           "--file", "${_DOCKERFILE}",
           "${_CODE_DIR}"]

logsBucket: "gs://${_BUCKET_NAME}"

options:
  dynamic_substitutions: true
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: E2_HIGHCPU_32
  substitution_option: "ALLOW_LOOSE"

substitutions:
  _CODE_DIR: "./code"
  _DOCKERFILE: ""
  _PIP_INSTALL_ARG: ""
  _BASE_IMAGE: ""
  _IMAGE_NAME: ""
  _AR_DOCKER_REPO: ""
  _AR_PIP_REPO: ""
  _DOCKER_IMAGE: "${_AR_DOCKER_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"

images:
  - "${_DOCKER_IMAGE}"