steps:
  - name: "bash"
    id: PY_DIST_DIR
    script: |
      #!/usr/bin/env bash
      mkdir -p ${DIST_DIR}
      echo "Created ${DIST_DIR}"
  - name: "python"
    id: PY_PIP_DOWNLOAD
    entrypoint: "python3"
    args: ["-m", "pip", "download",
           "--no-deps",
           "--dest", "${_DIST_DIR}",
           "--extra-index-url", "${_AR_PIP_REPO}/simple/",
           "${_PIP_PKG_ARG}"]
  - name: "gcr.io/cloud-builders/docker"
    id: DOCKER_BUILD
    args: ["build",
           "--pull",
           "--no-cache",
           "--progress", "plain",
           "--build-arg", "BASE_IMAGE=${_BASE_IMAGE}",
           "--build-arg", "DIST_DIR=${_DIST_DIR}",
           "--tag", "${_IMAGE_NAME}",
           "--tag", "${_DOCKER_IMAGE_LATEST}",
           "--tag", "${_DOCKER_IMAGE_SHA}",
           "--file", "${_DOCKERFILE}",
           "."]

logsBucket: "gs://${_BUCKET_NAME}/cloudbuild_logs/docker"

options:
  dynamic_substitutions: true
  env:
    - "DIST_DIR=${_DIST_DIR}"
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: UNSPECIFIED
  substitution_option: "ALLOW_LOOSE"

substitutions:
  _DIST_DIR: "dist"
  _DOCKERFILE: ""
  _PIP_PKG_ARG: ""
  _BASE_IMAGE: ""
  _IMAGE_NAME: ""
  _AR_DOCKER_REPO: ""
  _AR_PIP_REPO: ""
  _PIP_EXTRA_INDEX_URL: "${_AR_PIP_REPO}/simple/"
  _DOCKER_IMAGE_LATEST: "${_AR_DOCKER_REPO}/${_IMAGE_NAME}:latest"
  _DOCKER_IMAGE_SHA: "${_AR_DOCKER_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"

images:
  - "${_DOCKER_IMAGE_LATEST}"
  - "${_DOCKER_IMAGE_SHA}"