steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: IMAGE_DEPLOY
    args: ["run", "deploy", "${_SERVICE_NAME}", "${_IMAGE_URL}", "--region", "${LOCATION}"]
logsBucket: "gs://${_BUCKET_NAME}/cloudbuild_logs/${TRIGGER_NAME}"
options:
  dynamic_substitutions: true
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: UNSPECIFIED
  substitution_option: "ALLOW_LOOSE"
substitutions:
  _SERVICE_NAME: ""
  _IMAGE_URL: ""
