steps:
  - name: "hashicorp/terraform:1.3.7"
    id: TERRAFORM_INIT
    entrypoint: "sh"
    args: ["-c", "terraform -chdir=terraform/cicd init -upgrade"]
  - name: "hashicorp/terraform:1.3.7"
    id: TERRAFORM_PLAN
    entrypoint: "sh"
    args: ["-c", "terraform -chdir=terraform/cicd plan ${_TF_PLAN_ARGS} -out=${_TF_PLAN_FILE}"]
  - name: "hashicorp/terraform:1.3.7"
    id: TERRAFORM_APPLY
    entrypoint: "sh"
    args: ["-c", "terraform -chdir=terraform/cicd apply ${_TF_PLAN_FILE}"]
  - name: "gcr.io/cloud-builders/gcloud"
    id: BUILD_PYTHON
    args: [ "builds", "triggers", "run", "${_PYTHON_BUILD_TRIGGER}",
            "--region", "${LOCATION}",
            "--branch", "${BRANCH_NAME}" ]

logsBucket: "gs://${_BUCKET_NAME}/cloudbuild_logs/tf_cicd"

options:
  dynamic_substitutions: true
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: UNSPECIFIED
  substitution_option: "ALLOW_LOOSE"

substitutions:
  _TF_PLAN_ARGS: ""
  _TF_PLAN_FILE: "${SHORT_SHA}_tf_plan.out"
  _PYTHON_BUILD_TRIGGER: ""

artifacts:
  objects:
    location: "gs://${_BUCKET_NAME}/${REPO_NAME}-${BRANCH_NAME}/${$TRIGGER_NAME}/${BUILD_ID}"
    paths:
      - "${_TF_PLAN_FILE}"
