# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: pretty-format-json
    args: ["--autofix"]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/python-poetry/poetry
  rev: 1.4.0
  hooks:
  - id: poetry-check
- repo: local
  hooks:
  - id: black
    name: black (core)
    types: [python]
    language: system
    entry: bash -c "pushd code/core && poetry run black src tests; popd"
  - id: black
    name: black (cli)
    types: [python]
    language: system
    entry: bash -c "pushd code/cli && poetry run black src tests ; popd"
  - id: black
    name: black (service)
    types: [python]
    language: system
    entry: bash -c "pushd code/service && poetry run black src tests ; popd"
- repo: local
  hooks:
  - id: isort
    name: isort (core)
    types: [python]
    language: system
    entry: bash -c "pushd code/core && poetry run isort src tests ; popd"
  - id: isort
    name: isort (cli)
    types: [python]
    language: system
    entry: bash -c "pushd code/cli && poetry run isort src tests ; popd"
  - id: isort
    name: isort (service)
    types: [python]
    language: system
    entry: bash -c "pushd code/service && poetry run isort src tests ; popd"
#- repo: local
#  hooks:
#  - id: docformatter
#    name: docformatter (core)
#    types: [python]
#    language: system
#    entry: bash -c "pushd code/core && poetry run docformatter src tests ; popd"
#  - id: docformatter
#    name: docformatter (cli)
#    types: [python]
#    language: system
#    entry: bash -c "pushd code/cli && poetry run docformatter src tests ; popd"
#  - id: docformatter
#    name: docformatter (service)
#    types: [python]
#    language: system
#    entry: bash -c "pushd code/service && poetry run docformatter src tests ; popd"
- repo: local
  hooks:
  - id: vulture
    name:  vulture (core)
    language: system
    types: [python]
    entry: bash -c "pushd code/core && poetry run vulture ; popd"
  - id: vulture
    name:  vulture (cli)
    language: system
    types: [python]
    entry: bash -c "pushd code/cli && poetry run vulture ; popd"
  - id: vulture
    name:  vulture (service)
    language: system
    types: [python]
    entry: bash -c "pushd code/service && poetry run vulture ; popd"
- repo: local
  hooks:
  - id: pylint
    name: pylint (core)
    language: system
    types: [python]
    entry: bash -c "pushd code/core && poetry run pylint src tests ; popd"
  - id: pylint
    name: pylint (cli)
    language: system
    types: [python]
    entry: bash -c "pushd code/cli && poetry run pylint src tests ; popd"
  - id: pylint
    name: pylint (service)
    language: system
    types: [python]
    entry: bash -c "pushd code/service && poetry run pylint src tests ; popd"
