steps:
  - name: "bash"
    id: PY_DIST_DIR
    script: |
      #!/usr/bin/env bash
      mkdir -p ${DIST_DIR}
      echo "Created ${DIST_DIR}"
  - name: "python"
    id: PY_PIP_DOWNLOAD
    script: |
      #!/usr/bin/env bash

      echo "Downloading packages in <${PIP_PKG_LST}>"
      read -a PKG_LST <<< ${PIP_PKG_LST//@/ }
      for PKG in ${PKG_LST[@]}
      do
        echo "Downloading <${PKG}> from <${PIP_EXTRA_INDEX_URL}> into <${DIST_DIR}>"
        python3 -m pip download \
          --no-deps \
          --dest ${DIST_DIR} \
          --extra-index-url ${PIP_EXTRA_INDEX_URL} \
          ${PKG}
      done
  - name: "gcr.io/cloud-builders/docker"
    id: DOCKER_BUILD
    args: ["build", "--pull", "--no-cache", "--progress", "plain",
      "--build-arg", "BASE_IMAGE=${_BASE_IMAGE}",
      "--build-arg", "DIST_DIR=${_DIST_DIR}",
      "--build-arg", "CR_CONCURRENCY=${_CR_CONCURRENCY}",
      "--build-arg", "PY_PACKAGE=${_PY_PACKAGE}",
      "--tag", "${_IMAGE_NAME}",
      "--tag", "${_REMOTE_IMAGE_LATEST}",
      "--tag", "${_REMOTE_IMAGE_SHA}",
      "--file", "${_DOCKERFILE}",
      "."]
  - name: "gcr.io/cloud-builders/docker"
    id: DOCKER_PUSH_SHA
    args: ["push", "${_REMOTE_IMAGE_SHA}"]
  - name: "gcr.io/cloud-builders/docker"
    id: DOCKER_PUSH_LATEST
    args: ["push", "${_REMOTE_IMAGE_LATEST}"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: WAIT_FOR_RUN_READY
    entrypoint: "bash"
    args: ["-c", "apt-get install -y jq; ${_WAIT_SCRIPT} --project ${PROJECT_ID} --region ${LOCATION} --service ${_SERVICE_NAME}"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: IMAGE_DEPLOY
    entrypoint: "gcloud"
    args: ["run", "deploy", "${_SERVICE_NAME}",
      "--image", "${_REMOTE_IMAGE_SHA}",
      "--region", "${LOCATION}"]
logsBucket: "gs://${_BUCKET_NAME}/cloudbuild_logs/${TRIGGER_NAME}"
options:
  dynamic_substitutions: true
  env:
    - "DIST_DIR=${_DIST_DIR}"
    - "PIP_PKG_LST=${_PIP_PKG_LST}"
    - "PIP_EXTRA_INDEX_URL=${_PIP_EXTRA_INDEX_URL}"
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: UNSPECIFIED
  substitution_option: "ALLOW_LOOSE"
substitutions:
  _DIST_DIR: "dist"
  _DOCKERFILE: ""
  _PIP_PKG_LST: ""
  _BASE_IMAGE: ""
  _IMAGE_NAME: ""
  _AR_DOCKER_REPO: ""
  _AR_PIP_REPO: ""
  _PIP_EXTRA_INDEX_URL: "${_AR_PIP_REPO}/simple/"
  _REMOTE_IMAGE_LATEST: "${_AR_DOCKER_REPO}/${_IMAGE_NAME}:latest"
  _REMOTE_IMAGE_SHA: "${_AR_DOCKER_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
  _SERVICE_NAME: ""
  _WAIT_SCRIPT: ""
  _CR_CONCURRENCY: ""
  _PY_PACKAGE: ""
images:
  - "${_REMOTE_IMAGE_LATEST}"
  - "${_REMOTE_IMAGE_SHA}"
