steps:
  - name: "bash"
    id: BACKEND_TF
    entrypoint: "bash"
    args: ["-c", "sed -e \"s/@@BUCKET_NAME@@/${_TF_BUCKET_NAME}/g\" -e \"s/@@MODULE@@/${_TF_MODULE}/g\" -e \"s/@@REGION@@/${LOCATION}/g\" ${_TF_BACKEND_TF_TMPL} > ${_TF_DIR}/backend.tf"]
  - name: "hashicorp/terraform:1.3.7"
    id: TERRAFORM_INIT
    entrypoint: "sh"
    args: ["-c", "terraform -chdir=${_TF_DIR} init -upgrade"]
  - name: "hashicorp/terraform:1.3.7"
    id: TERRAFORM_PLAN
    entrypoint: "sh"
    args: ["-c", "terraform -chdir=${_TF_DIR} plan ${_TF_PLAN_ARGS} -out=${_TF_PLAN_FILE}"]
  - name: "hashicorp/terraform:1.3.7"
    id: TERRAFORM_APPLY
    entrypoint: "sh"
    args: ["-c", "terraform -chdir=${_TF_DIR} apply ${_TF_PLAN_FILE}"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: BUILD_PYTHON
    script: |
      #!/usr/bin/env bash

      gcloud builds triggers run ${PYTHON_BUILD_TRIGGER} --region ${LOCATION} --branch ${BRANCH_NAME}
    entrypoint: "gcloud"
    args: ["builds", "triggers", "run", "${_PYTHON_BUILD_TRIGGER}", "--region", "${LOCATION}",
      "--branch", "${BRANCH_NAME}"]
    waitFor:
      - TERRAFORM_APPLY
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: BUILD_YAAS_INFRA
    entrypoint: "gcloud"
    args: ["builds", "triggers", "run", "${_INFRA_BUILD_TRIGGER}", "--region", "${LOCATION}",
      "--branch", "${BRANCH_NAME}"]
    waitFor:
      - TERRAFORM_APPLY
logsBucket: "gs://${_BUCKET_NAME}/cloudbuild_logs/${TRIGGER_NAME}"
options:
  dynamic_substitutions: true
  env:
    - "PYTHON_BUILD_TRIGGER_LST=${_PYTHON_BUILD_TRIGGER_LST}"
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: UNSPECIFIED
  substitution_option: "ALLOW_LOOSE"
substitutions:
  _TF_BUCKET_NAME: ""
  _TF_MODULE: ""
  _TF_BACKEND_TF_TMPL: ""
  _TF_DIR: "terraform/${_TF_MODULE}"
  _TF_PLAN_ARGS: ""
  _TF_PLAN_FILE: "${SHORT_SHA}_tf_plan.out"
  _PYTHON_BUILD_TRIGGER_LST: ""
  _INFRA_BUILD_TRIGGER: ""
