steps:
  - name: "bash"
    id: PY_DIST_DIR
    script: |
      #!/usr/bin/env bash
      mkdir -p ${DIST_DIR}
    dir: "${_CODE_DIR}"
  - name: "python"
    id: PY_MINIMUM
    entrypoint: "python3"
    args: ["-m", "pip", "install", "--user", "--upgrade", "pip", "wheel", "setuptools"]
    waitFor:
      - PY_DIST_DIR
  - name: "python"
    id: PY_BUILD_DEPENDENCIES
    entrypoint: "python3"
    args: ["-m", "pip", "install", "--user", ".[all]"]
    dir: "${_CODE_DIR}"
  - name: "python"
    id: PY_BUILD
    entrypoint: "python3"
    args: ["./setup.py", "build", "--force"]
    dir: "${_CODE_DIR}"
  - name: "python"
    id: PY_LINT
    entrypoint: "python3"
    args: ["-m", "pylint", "--output-format=json:./${_DIST_DIR}/${_PYTHON_PYLINT_FILE},colorized",
      "--disable=use-dict-literal", "setup.py", "tests", "yaas"]
    dir: "${_CODE_DIR}"
    waitFor:
      - PY_BUILD
  - name: "python"
    id: PY_TESTS
    entrypoint: "python3"
    args: ["-m", "pytest", "-m", "not doesnt_work_cloudbuild", "--junitxml=./${_DIST_DIR}/${_PYTHON_PYTEST_FILE}"]
    dir: "${_CODE_DIR}"
    waitFor:
      - PY_BUILD
  - name: "python"
    id: PY_WHEEL
    script: |
      #!/usr/bin/env bash
      BUILD_NUMBER=$(date -u +%s)
      python3 ./setup.py bdist_wheel \
        --universal \
        --build-number ${BUILD_NUMBER} \
        --dist-dir ${DIST_DIR}
    dir: "${_CODE_DIR}"
  - name: "gcr.io/cloud-builders/gcloud"
    id: BUILD_DOCKER
    args: ["builds", "triggers", "run", "${_DOCKER_BUILD_TRIGGER}", "--region", "${LOCATION}",
      "--branch", "${BRANCH_NAME}"]
logsBucket: "gs://${_BUCKET_NAME}/cloudbuild_logs/${TRIGGER_NAME}"
options:
  dynamic_substitutions: true
  env:
    - "DIST_DIR=${_DIST_DIR}"
  logging: LEGACY
  logStreamingOption: STREAM_DEFAULT
  machineType: E2_HIGHCPU_8
substitutions:
  _CODE_DIR: "./code"
  _DIST_DIR: "dist"
  _PYTHON_PYTEST_FILE: "${SHORT_SHA}_test_log.xml"
  _PYTHON_PYLINT_FILE: "${SHORT_SHA}_lint_log.json"
  _PYTHON_REPO_NAME: ""
  _AR_PIP_REPO: ""
  _DOCKER_BUILD_TRIGGER: ""
artifacts:
  objects:
    location: "gs://${_BUCKET_NAME}/${REPO_NAME}-${BRANCH_NAME}/${TRIGGER_NAME}/${BUILD_ID}"
    paths:
      - "${_CODE_DIR}/${_DIST_DIR}/**"
  pythonPackages:
    - repository: "${_AR_PIP_REPO}"
      paths: ["${_CODE_DIR}/${_DIST_DIR}/*.whl"]
